steps:
  # Step 1: mempersiapkan library/ dependencies
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: bash
    args:
      - -c
      - |
        if [ ! -d "node_modules" ]; then
          echo "Installing dependencies..."
          npm ci
        else
          echo "Skipping npm install, node_modules exists."
        fi
    dir: "frontend"
    volumes:
      - name: "npm-cache"
        path: /root/.npm

  # Step 2: membangun frontend
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: bash
    args:
      - -c
      - |
        npm run build
    dir: "frontend"
    volumes:
      - name: "npm-cache"
        path: /root/.npm

  # Step 3: Deploy ke App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["app", "deploy", "app.yaml", "--quiet"]
    dir: "frontend"

options:
  logging: CLOUD_LOGGING_ONLY