version: '3.8'

services:
  # Backend Service
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_USER=petshop_user
      - DB_PASSWORD=petshop_password
      - DB_DATABASE=petshop_db
      - DB_PORT=3306
      - DB_DIALECT=mysql
      - JWT_SECRET=your_jwt_secret_here
      - NEXTCLOUD_URL=http://nextcloud
      - NEXTCLOUD_USER=admin
      - NEXTCLOUD_PASSWORD=admin123
    depends_on:
      - mysql
      - nextcloud
    networks:
      - petshop-network
    restart: unless-stopped

  # MySQL Database - Single instance for both apps
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: petshop_db
      MYSQL_USER: petshop_user
      MYSQL_PASSWORD: petshop_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - petshop-network
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  # NextCloud Service
  nextcloud:
    image: nextcloud:latest
    ports:
      - "8080:80"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=nextcloud_user
      - MYSQL_PASSWORD=nextcloud_password
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin123
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost nextcloud
    volumes:
      - nextcloud_data:/var/www/html
      - nextcloud_apps:/var/www/html/custom_apps
      - nextcloud_config:/var/www/html/config
      - nextcloud_themes:/var/www/html/themes
    depends_on:
      - mysql
    networks:
      - petshop-network
    restart: unless-stopped

volumes:
  mysql_data:
  nextcloud_data:
  nextcloud_apps:
  nextcloud_config:
  nextcloud_themes:

networks:
  petshop-network:
    driver: bridge